import { NextResponse } from 'next/server'
import dbConnect from '@/lib/mongodb'
import { InterviewSession } from '@/models/InterviewSession.model'
import { InterviewResult } from '@/models/InterviewResult.model'
import { protect } from '@/middlewares/auth.middleware'
import { asyncHandler } from '@/lib/asyncHandler'

export const GET = asyncHandler(async (req, { params }) => {
    await dbConnect()

    // 1. Authenticate user
    const user = await protect(req)
    const { id: sessionId } = await params

    // 2. Fetch session and verify ownership/status
    const session = await InterviewSession.findById(sessionId)
    if (!session) {
        return NextResponse.json({ error: 'Session not found' }, { status: 404 })
    }

    if (session.userId.toString() !== user.id) {
        return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    if (session.status !== 'completed' && session.status !== 'terminated') {
        return NextResponse.json(
            {
                error: 'BAD_REQUEST',
                message: 'Only completed or terminated sessions can be exported.',
            },
            { status: 400 }
        )
    }

    // 3. Fetch result data
    const result = await InterviewResult.findOne({ sessionId })
    if (!result) {
        return NextResponse.json({ error: 'Result data not found' }, { status: 404 })
    }

    // 4. Generate Markdown report
    const report = `# CodeArena Interview Report
# ${result.problemTitle || 'Technical Interview Session'}

## 📊 Performance Overview
- **Overall Score:** ${result.overallScore}/100
- **Communication:** ${result.communicationScore}/100
- **Technical Approach:** ${result.approachScore}/100
- **Code Quality:** ${result.codeQualityScore}/100

## 🤖 AI Executive Summary
${result.aiSummary}

## 🌟 Key Strengths
${result.strengths?.map((s) => `- ${s}`).join('\n') || 'No specific strengths noted.'}

## 🚀 Growth Areas
${result.areasToImprove?.map((a) => `- ${a}`).join('\n') || 'No specific growth areas noted.'}

---
**Session Metadata**
- **Session ID:** ${sessionId}
- **User ID:** ${user.id}
- **Date:** ${new Date(result.createdAt).toLocaleString()}
- **Platform:** CodeArena Live AI Interview

---
*Generated by CodeArena Intelligence*
`

    // 5. Return as a downloadable file
    const filename = `Interview_Report_${sessionId}.md`

    return new NextResponse(report, {
        headers: {
            'Content-Type': 'text/markdown',
            'Content-Disposition': `attachment; filename="${filename}"`,
        },
    })
})
