'use client'

import React, { useEffect, useState } from 'react'
import { format } from 'date-fns'
import {
    Award,
    Download,
    FileText,
    ChevronLeft,
    CheckCircle2,
    AlertCircle,
    TrendingUp,
    MessageSquare,
    ClipboardList,
} from 'lucide-react'
import Link from 'next/link'

export default function ScorecardView({ sessionId }) {
    const [result, setResult] = useState(null)
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState(null)

    useEffect(() => {
        const fetchResult = async () => {
            try {
                const res = await fetch(`/api/interview/sessions/${sessionId}/result`)
                const json = await res.json()
                if (json.success) {
                    setResult(json.data)
                } else {
                    setError(json.message || 'Failed to load result')
                }
            } catch (err) {
                setError('Network error. Please try again.')
            } finally {
                setLoading(false)
            }
        }
        fetchResult()
    }, [sessionId])

    const exportMarkdown = () => {
        if (!result) return

        const md = `# Interview Scorecard: ${result.problemTitle || 'Technical Interview'}
**Date:** ${format(new Date(result.createdAt), 'PPPP')}
**Score:** ${result.overallScore}/100

## Performance Breakdown
- **Communication:** ${result.communicationScore}/100
- **Approach:** ${result.approachScore}/100
- **Code Quality:** ${result.codeQualityScore}/100

## AI Executive Summary
${result.aiSummary}

## Key Strengths
${result.strengths?.map((s) => `- ${s}`).join('\n')}

## Areas to Improve
${result.areasToImprove?.map((a) => `- ${a}`).join('\n')}

---
*Generated by CodeArena Live AI Interview System*
*Session ID: ${sessionId}*
`

        const blob = new Blob([md], { type: 'text/markdown' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `Interview_Scorecard_${sessionId}.md`
        a.click()
        URL.revokeObjectURL(url)
    }

    const exportPDF = () => {
        window.print()
    }

    if (loading) {
        return (
            <div className="flex min-h-screen flex-col items-center justify-center bg-[#0a0a0a]">
                <div className="relative flex h-20 w-20 items-center justify-center">
                    <div className="absolute inset-0 animate-ping rounded-full bg-blue-500/20" />
                    <Award className="h-10 w-10 animate-bounce text-blue-500" />
                </div>
                <p className="mt-4 font-bold tracking-tight text-slate-400">
                    Analysing your performance...
                </p>
            </div>
        )
    }

    if (error || !result) {
        return (
            <div className="flex min-h-screen flex-col items-center justify-center bg-[#0a0a0a] p-6 text-center">
                <div className="mb-4 rounded-full bg-red-500/10 p-4 text-red-500">
                    <AlertCircle size={40} />
                </div>
                <h2 className="text-xl font-bold text-white">Results Pending</h2>
                <p className="mt-2 max-w-sm text-slate-400">
                    Your interview evaluation is still being processed. Please check back in a few
                    minutes.
                </p>
                <Link
                    href="/interview/history"
                    className="mt-8 rounded-xl bg-slate-800 px-6 py-2.5 text-sm font-bold text-white transition-all hover:bg-slate-700"
                >
                    Back to History
                </Link>
            </div>
        )
    }

    return (
        <div className="min-h-screen bg-[#0a0a0a] pb-20 text-white selection:bg-blue-500/30">
            {/* Header - Hidden on Print */}
            <header className="sticky top-0 z-40 border-b border-white/5 bg-[#0d0d0d]/80 px-6 py-4 backdrop-blur-xl print:hidden">
                <div className="mx-auto flex max-w-5xl items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Link
                            href="/interview/history"
                            className="group flex h-10 w-10 items-center justify-center rounded-xl border border-white/5 bg-white/5 transition-all hover:bg-white/10"
                        >
                            <ChevronLeft className="h-5 w-5 text-slate-400 transition-transform group-hover:-translate-x-0.5" />
                        </Link>
                        <div>
                            <h1 className="text-sm font-black tracking-tight text-white uppercase sm:text-base">
                                Scorecard
                            </h1>
                            <p className="text-[10px] font-bold tracking-widest text-slate-500 uppercase">
                                {result.problemTitle || 'Session Result'}
                            </p>
                        </div>
                    </div>

                    <div className="flex items-center gap-2">
                        <button
                            onClick={exportMarkdown}
                            className="flex items-center gap-2 rounded-xl bg-slate-800 px-4 py-2 text-xs font-bold transition-all hover:bg-slate-700 active:scale-95"
                        >
                            <FileText size={14} className="text-blue-400" />
                            <span className="hidden sm:inline">Export MD</span>
                        </button>
                        <button
                            onClick={exportPDF}
                            className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-xs font-bold shadow-lg shadow-blue-600/20 transition-all hover:bg-blue-500 active:scale-95"
                        >
                            <Download size={14} />
                            <span className="hidden sm:inline">Download PDF</span>
                        </button>
                    </div>
                </div>
            </header>

            {/* Main Scorecard Content */}
            <main className="mx-auto max-w-4xl px-6 pt-12 print:pt-0">
                {/* Hero Section: Overall Score */}
                <section className="relative overflow-hidden rounded-[2.5rem] border border-white/5 bg-gradient-to-br from-slate-900 to-black p-8 shadow-2xl md:p-12">
                    <div className="absolute top-0 right-0 h-64 w-64 bg-blue-500/5 blur-[100px]" />

                    <div className="flex flex-col items-center gap-8 md:flex-row md:justify-between">
                        <div className="space-y-4 text-center md:text-left">
                            <div className="inline-flex items-center gap-2 rounded-full border border-blue-500/20 bg-blue-500/10 px-4 py-1.5 text-[10px] font-black tracking-[0.2em] text-blue-400 uppercase">
                                <TrendingUp size={12} />
                                Performance Insight
                            </div>
                            <h2 className="text-4xl font-black tracking-tight text-white md:text-6xl">
                                Exceptional <br className="hidden md:block" /> Results.
                            </h2>
                            <p className="max-w-md text-sm leading-relaxed text-slate-400 md:text-base">
                                You demonstrated strong technical proficiency and clear
                                communication during this {result.problemTitle} interview.
                            </p>
                        </div>

                        <div className="relative flex h-48 w-48 items-center justify-center rounded-full border-[10px] border-white/5 bg-slate-900/50 shadow-inner md:h-56 md:w-56">
                            {/* Score Circle */}
                            <svg className="absolute inset-0 h-full w-full -rotate-90 transform">
                                <circle
                                    cx="50%"
                                    cy="50%"
                                    r="44%"
                                    className="fill-none stroke-blue-500/10"
                                    strokeWidth="10"
                                />
                                <circle
                                    cx="50%"
                                    cy="50%"
                                    r="44%"
                                    className="fill-none stroke-blue-500 transition-all duration-1000 ease-out"
                                    strokeWidth="10"
                                    strokeDasharray="276"
                                    strokeDashoffset={
                                        276 - (276 * (result.overallScore || 0)) / 100
                                    }
                                    strokeLinecap="round"
                                />
                            </svg>
                            <div className="text-center">
                                <span className="block text-5xl font-black text-white md:text-6xl">
                                    {result.overallScore}
                                </span>
                                <span className="text-[10px] font-bold tracking-widest text-slate-500 uppercase">
                                    Final Score
                                </span>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Grid: Detailed Ratings */}
                <section className="mt-8 grid gap-6 md:grid-cols-3">
                    {[
                        {
                            label: 'Communication',
                            val: result.communicationScore,
                            color: 'text-indigo-400',
                        },
                        {
                            label: 'Technical Approach',
                            val: result.approachScore,
                            color: 'text-blue-400',
                        },
                        {
                            label: 'Code Quality',
                            val: result.codeQualityScore,
                            color: 'text-emerald-400',
                        },
                    ].map((item, i) => (
                        <div
                            key={i}
                            className="rounded-3xl border border-white/5 bg-[#0d0d0d] p-6 transition-all hover:bg-white/5"
                        >
                            <span className="text-[10px] font-black tracking-widest text-slate-500 uppercase">
                                {item.label}
                            </span>
                            <div className="mt-2 flex items-baseline gap-2">
                                <span className={`text-3xl font-black ${item.color}`}>
                                    {item.val}
                                </span>
                                <span className="text-sm font-bold text-slate-700">/ 100</span>
                            </div>
                            <div className="mt-4 h-1.5 w-full overflow-hidden rounded-full bg-white/5">
                                <div
                                    className={`h-full transition-all duration-700 ${item.color.replace('text-', 'bg-')}`}
                                    style={{ width: `${item.val}%` }}
                                />
                            </div>
                        </div>
                    ))}
                </section>

                {/* AI Summary */}
                <section className="mt-12 space-y-4">
                    <div className="flex items-center gap-3">
                        <MessageSquare className="h-5 w-5 text-blue-500" />
                        <h3 className="text-sm font-black tracking-widest text-white uppercase">
                            AI Review Summary
                        </h3>
                    </div>
                    <div className="rounded-3xl border border-white/5 bg-[#0d0d0d] p-8 text-sm leading-relaxed text-slate-400 md:text-base">
                        {result.aiSummary}
                    </div>
                </section>

                {/* Strengths & Improvements */}
                <section className="mt-12 grid gap-8 md:grid-cols-2">
                    {/* Strengths */}
                    <div className="space-y-4">
                        <div className="flex items-center gap-3">
                            <CheckCircle2 className="h-5 w-5 text-emerald-500" />
                            <h3 className="text-sm font-black tracking-widest text-white uppercase">
                                Key Strengths
                            </h3>
                        </div>
                        <div className="space-y-3">
                            {result.strengths?.map((s, i) => (
                                <div
                                    key={i}
                                    className="flex gap-3 rounded-2xl bg-emerald-500/5 p-4 text-sm text-emerald-400/80"
                                >
                                    <span className="font-mono opacity-50">
                                        {String(i + 1).padStart(2, '0')}
                                    </span>
                                    {s}
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Improvements */}
                    <div className="space-y-4">
                        <div className="flex items-center gap-3">
                            <ClipboardList className="h-5 w-5 text-yellow-500" />
                            <h3 className="text-sm font-black tracking-widest text-white uppercase">
                                Growth Areas
                            </h3>
                        </div>
                        <div className="space-y-3">
                            {result.areasToImprove?.map((a, i) => (
                                <div
                                    key={i}
                                    className="flex gap-3 rounded-2xl bg-yellow-500/5 p-4 text-sm text-yellow-400/80"
                                >
                                    <span className="font-mono opacity-50">
                                        {String(i + 1).padStart(2, '0')}
                                    </span>
                                    {a}
                                </div>
                            ))}
                        </div>
                    </div>
                </section>

                {/* Footer Credits */}
                <footer className="text-slate-750 mt-20 border-t border-white/5 pt-8 text-center text-[10px] font-bold tracking-widest uppercase">
                    CodeArena Artificial Intelligence • Session ID: {sessionId}
                </footer>
            </main>

            {/* Print Styles */}
            <style jsx global>{`
                @media print {
                    @page {
                        margin: 1cm;
                        size: A4;
                    }
                    body {
                        background: white !important;
                        color: black !important;
                    }
                    .bg-\\[\\#0a0a0a\\] {
                        background: white !important;
                    }
                    .bg-\\[\\#0d0d0d\\] {
                        background: #f8fafc !important;
                        border: 1px solid #e2e8f0 !important;
                    }
                    .text-white {
                        color: #0f172a !important;
                    }
                    .text-slate-400,
                    .text-slate-500 {
                        color: #475569 !important;
                    }
                    .border-white\\/5 {
                        border-color: #e2e8f0 !important;
                    }
                    .bg-gradient-to-br {
                        background: #f1f5f9 !important;
                        color: #0f172a !important;
                    }
                    .rounded-\\[2\\.5rem\\] {
                        border-radius: 12px !important;
                    }
                    .shadow-2xl,
                    .shadow-lg {
                        box-shadow: none !important;
                    }
                    .print\\:hidden {
                        display: none !important;
                    }
                    button {
                        display: none !important;
                    }
                }
            `}</style>
        </div>
    )
}
